/* eslint-disable @next/next/no-sync-scripts */
import { AuthProvider } from '@/contexts/AuthContext'
import type { Metadata } from 'next'
import { Roboto_Flex as Roboto, Inter } from 'next/font/google'

import './globals.css'

const roboto = Roboto({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AuthProvider>
      <html lang="en" className="font">
        <body className={`${roboto.className} grid min-h-screen text-zinc-700`}>
          {children}
        </body>
      </html>
    </AuthProvider>
  )
}
