import type { Metadata } from 'next'
import { Inter, Roboto_Flex as Roboto } from 'next/font/google'
import './globals.css'

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '700'],
})

const roboto = Roboto({ subsets: ['latin'], variable: '--font-roboto' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="font">
      <body className={`${roboto.className} grid min-h-screen text-zinc-700`}>
        {children}
      </body>
    </html>
  )
}
